services:
  dev-web:
    image: ${APP_IMAGE:-speakeasy:local}
    container_name: speakeasy
    env_file: .env.production
    restart: always
    networks:
      - liboboa
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - logs:/javarun/logs
      - data:/data
    ports:
      - "8600:8000"

volumes:
  logs:
  data:

networks:
  liboboa:
    name: liboboa
    external: true
